[project]
name = "physiotrack"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Cyrille NDOUMBE", email = "candoumbe@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "opentelemetry-api>=1.44.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.44.0",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "opentelemetry-instrumentation-logging>=0.65b0",
    "opentelemetry-sdk>=1.44.0",
    "uvicorn[standard]",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "httpx",
    "pytest",
    "ruff>=0.16.7",
]
